### ISSUE TITLE
No right_arrow.png file

### ISSUE THREAD

**Issue by cravisjan97** [IsaacGuan/Functionality-Aware-Model-Evolution#1]
I tried to run fameBase.sln file on Visual Studio and I get the following error:

`Invalid Resx file. Could not find file 'C:\Users\csundaram\Desktop\FAME-master\FAME-master\icons\right_arrow.png'. Line 123, position 5.`

Any idea on how to fix this

**Comment by IsaacGuan** [comment]
Hi, the `icons` folder was mistakenly excluded by `.gitignore`. I have already included the missing icons today in the latest commit to this repository.
